.PHONY: all
all: compute login manager

.PHONY: compute
compute: 
	$(MAKE) -C compute all

.PHONY: arm
arm: 
	$(MAKE) -C arm all

.PHONY: login
login: 
	$(MAKE) -C login all

.PHONY: manager
manager: 
	$(MAKE) -C manager all
